const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
const CLEAR_ERRORS = "CLEAR_ERRORS";

const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export {
	ALL_PRODUCT_REQUEST,
	ALL_PRODUCT_FAIL,
	ALL_PRODUCT_SUCCESS,
	CLEAR_ERRORS,
	PRODUCT_DETAILS_REQUEST,
	PRODUCT_DETAILS_SUCCESS,
	PRODUCT_DETAILS_FAIL,
};
